export const MEMBERS = [
  {
    name: "frank",
    description: "Co-founder, Tech Lead",
    twitter: "https://twitter.com/Frankc_eth",
    farcaster: "https://farcaster.xyz/frankk",
    image: "/team/frank.jpg",
  },
  {
    name: "limone",
    description: "Co-founder, Product Lead",
    twitter: "https://twitter.com/limone_eth",
    farcaster: "https://farcaster.xyz/limone.eth",
    url: "https://limone.lol",
    image: "/team/limone.png",
  },
  {
    name: "orbulo",
    description: "Co-founder, Full Stack Developer",
    twitter: "https://twitter.com/orbuloeth",
    farcaster: "https://farcaster.xyz/orbulo",
    url: "https://paolorollo.dev",
    image: "/team/orbulo.jpg",
  },
  {
    name: "flurry",
    description: "Finance",
    twitter: "https://twitter.com/mctflurryy",
    farcaster: "https://farcaster.xyz/mctflurry",
    image: "/team/flurry.jpg",
  },
  {
    name: "fraye",
    description: "Full Stack Developer",
    twitter: "https://twitter.com/itsmide_eth",
    farcaster: "https://farcaster.xyz/itsmide.eth",
    url: "https://midena.dev",
    image: "/team/fraye.jpg",
  },
  {
    name: "stepome",
    description: "UX/UI Designer",
    twitter: "https://twitter.com/stefanopomelli",
    farcaster: "https://farcaster.xyz/stepome",
    url: "https://stefanopomelli.com/",
    image: "/team/stepome.jpg",
  },
  {
    name: "bianc8",
    description: "Full Stack Developer",
    twitter: "https://twitter.com/bianc8_eth",
    farcaster: "https://farcaster.xyz/bianc8",
    url: "https://biancotto.eu",
    image: "/team/bianc8.jpg",
  },
  {
    name: "blackicon",
    description: "Full Stack Developer",
    twitter: "https://twitter.com/TBlackicon",
    farcaster: "https://farcaster.xyz/blackicon.eth",
    image: "/team/blackicon.png",
  },
  {
    name: "caso",
    description: "Full Stack Developer",
    twitter: "https://twitter.com/casoxbt",
    farcaster: "https://farcaster.xyz/0xcaso",
    url: "https://matteocasonato.com/",
    image: "/team/caso.png",
  },
  {
    name: "drone",
    description: "Solidity Developer",
    twitter: "https://twitter.com/SolidityDrone",
    farcaster: "https://farcaster.xyz/drone",
    image: "/team/drone.jpg",
  },
];
