import { Project } from "@/types";
import {
  Globe,
  Building2,
  Users,
  Trophy,
  Medal,
  Gamepad2,
  Music,
  Film,
  CreditCard,
  MessageSquare,
  MoreHorizontal,
  type LucideIcon,
} from "lucide-react";

export enum LINK_TYPE {
  WEBSITE = "Website",
  FARCASTER = "Farcaster",
  TWITTER = "Twitter",
  GITHUB = "Github",
  YOUTUBE = "Youtube Demo",
}

export const LINK_TYPE_ICONS: Record<LINK_TYPE, string> = {
  [LINK_TYPE.WEBSITE]: "/icons/dribble.svg",
  [LINK_TYPE.FARCASTER]: "/icons/farcaster.svg",
  [LINK_TYPE.TWITTER]: "/icons/twitter.svg",
  [LINK_TYPE.GITHUB]: "/icons/github.svg",
  [LINK_TYPE.YOUTUBE]: "/icons/youtube.svg",
};

export enum PROJECT_TAG {
  ALL = "All",
  INTERNAL = "Internal project",
  EXTERNAL = "Contractor project",
  SPORTS = "Sports",
  LEADERBOARDS = "Leaderboards",
  GAME = "Game",
  MUSIC = "Music",
  PODCASTS = "Podcasts",
  MOVIES = "Movies",
  LIVESTREAMS = "Livestreams",
  RADIO = "Radio",
  PAYMENTS = "Payments",
  SOCIAL = "Social",
  IDENTITY = "Identity",
  PRIVACY = "Privacy",
  BETS = "Bets",
  OTHER = "Other",
  STABLECOINS = "Stablecoins",
  MERCHANT = "Merchant",
  CROSS_CHAIN = "Cross-chain",
  HEALTH = "Health",
  FITNESS = "Fitness",
  NEWS = "News",
  CHECK_IN = "Check-in",
  IRL = "IRL",
  EVENTS = "Events",
}

// Define which tags to show in the filter UI
export const FILTER_TAGS = [
  PROJECT_TAG.ALL,
  PROJECT_TAG.INTERNAL,
  PROJECT_TAG.EXTERNAL,
  PROJECT_TAG.SPORTS,
  PROJECT_TAG.LEADERBOARDS,
  PROJECT_TAG.GAME,
  PROJECT_TAG.MUSIC,
  PROJECT_TAG.MOVIES,
  PROJECT_TAG.PAYMENTS,
  PROJECT_TAG.SOCIAL,
  PROJECT_TAG.OTHER,
] as const;

// Map filter tags to their icons
export const FILTER_TAG_ICONS: Partial<Record<PROJECT_TAG, LucideIcon>> = {
  [PROJECT_TAG.ALL]: Globe,
  [PROJECT_TAG.INTERNAL]: Building2,
  [PROJECT_TAG.EXTERNAL]: Users,
  [PROJECT_TAG.SPORTS]: Trophy,
  [PROJECT_TAG.LEADERBOARDS]: Medal,
  [PROJECT_TAG.GAME]: Gamepad2,
  [PROJECT_TAG.MUSIC]: Music,
  [PROJECT_TAG.MOVIES]: Film,
  [PROJECT_TAG.PAYMENTS]: CreditCard,
  [PROJECT_TAG.SOCIAL]: MessageSquare,
  [PROJECT_TAG.OTHER]: MoreHorizontal,
};

// Map filter tags to the actual tags they represent
export const TAGS_FILTERS: Record<PROJECT_TAG, PROJECT_TAG[]> = {
  [PROJECT_TAG.ALL]: [PROJECT_TAG.ALL],
  [PROJECT_TAG.INTERNAL]: [PROJECT_TAG.INTERNAL],
  [PROJECT_TAG.EXTERNAL]: [PROJECT_TAG.EXTERNAL],
  [PROJECT_TAG.SPORTS]: [PROJECT_TAG.SPORTS, PROJECT_TAG.BETS],
  [PROJECT_TAG.LEADERBOARDS]: [PROJECT_TAG.LEADERBOARDS],
  [PROJECT_TAG.GAME]: [PROJECT_TAG.GAME],
  [PROJECT_TAG.MUSIC]: [
    PROJECT_TAG.MUSIC,
    PROJECT_TAG.PODCASTS,
    PROJECT_TAG.LIVESTREAMS,
    PROJECT_TAG.RADIO,
  ],
  [PROJECT_TAG.MOVIES]: [PROJECT_TAG.MOVIES],
  [PROJECT_TAG.PAYMENTS]: [
    PROJECT_TAG.PAYMENTS,
    PROJECT_TAG.STABLECOINS,
    PROJECT_TAG.MERCHANT,
    PROJECT_TAG.CROSS_CHAIN,
  ],
  [PROJECT_TAG.SOCIAL]: [
    PROJECT_TAG.SOCIAL,
    PROJECT_TAG.IDENTITY,
    PROJECT_TAG.PRIVACY,
    PROJECT_TAG.CHECK_IN,
    PROJECT_TAG.IRL,
    PROJECT_TAG.EVENTS,
  ],
  [PROJECT_TAG.OTHER]: [
    PROJECT_TAG.OTHER,
    PROJECT_TAG.MERCHANT,
    PROJECT_TAG.CROSS_CHAIN,
    PROJECT_TAG.HEALTH,
    PROJECT_TAG.FITNESS,
    PROJECT_TAG.NEWS,
  ],
  // Map remaining tags to empty arrays (they won't show in filter UI)
  [PROJECT_TAG.BETS]: [],
  [PROJECT_TAG.PODCASTS]: [],
  [PROJECT_TAG.LIVESTREAMS]: [],
  [PROJECT_TAG.RADIO]: [],
  [PROJECT_TAG.IDENTITY]: [],
  [PROJECT_TAG.PRIVACY]: [],
  [PROJECT_TAG.STABLECOINS]: [],
  [PROJECT_TAG.MERCHANT]: [],
  [PROJECT_TAG.CROSS_CHAIN]: [],
  [PROJECT_TAG.HEALTH]: [],
  [PROJECT_TAG.FITNESS]: [],
  [PROJECT_TAG.NEWS]: [],
  [PROJECT_TAG.CHECK_IN]: [],
  [PROJECT_TAG.IRL]: [],
  [PROJECT_TAG.EVENTS]: [],
};

export const PROJECTS: Project[] = [
  {
    name: "Farville",
    slug: "farville",
    description:
      "A Farcaster mini-app game where you can plant, grow and harvest crop with your internet frens.",
    markdownPath: "content/farville.mdx",
    color: "#CCCCCC",
    image: "/projects/farville/preview.png",
    heroImage: "/projects/farville/hero.jpg",
    screenshotUrls: [
      {
        url: "/projects/farville/1.png",
        alt: "Farville onboarding",
        text: "1. Farville user onboarding flow",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/farville/2.png",
        alt: "Farville ranking",
        text: "2. Farville global rankings",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/farville/3.png",
        alt: "Farville streak",
        text: "3. Farville daily streak",
        width: 1080,
        height: 1920,
      },
    ],
    tags: [PROJECT_TAG.INTERNAL, PROJECT_TAG.GAME, PROJECT_TAG.LEADERBOARDS],
    homepage: true,
    links: [
      {
        type: LINK_TYPE.WEBSITE,
        url: "https://farville.farm",
      },
      {
        type: LINK_TYPE.FARCASTER,
        url: "https://farcaster.xyz/miniapps/WoLihpyQDh7w/farville",
      },
    ],
  },
  {
    name: "RevU",
    slug: "revu",
    description:
      "A Farcaster mini-app for TBA where you can create and share your own RevU.",
    markdownPath: "content/revu.mdx",
    color: "#6C3BF5",
    image: "/projects/revu/preview.png",
    tags: [PROJECT_TAG.EXTERNAL, PROJECT_TAG.MOVIES],
    homepage: true,
    links: [
      {
        type: LINK_TYPE.WEBSITE,
        url: "https://revu.decentralized.pictures",
      },
      {
        type: LINK_TYPE.FARCASTER,
        url: "https://farcaster.xyz/miniapps/cdGXMlMJRvVm/revu",
      },
    ],
  },
  {
    name: "Checkmates",
    slug: "checkmates",
    description: "Classic chess. Social stakes. Native to Farcaster.",
    markdownPath: "content/checkmates.mdx",
    color: "#6C3BF5",
    image: "/projects/checkmates/preview.png",
    heroImage: "/projects/checkmates/hero.png",
    tags: [
      PROJECT_TAG.EXTERNAL,
      PROJECT_TAG.GAME,
      PROJECT_TAG.BETS,
      PROJECT_TAG.LEADERBOARDS,
      PROJECT_TAG.LIVESTREAMS,
      PROJECT_TAG.SOCIAL,
    ],
    screenshotUrls: [
      {
        url: "/projects/checkmates/1.png",
        alt: "Checkmates Live Chess Game",
        text: "1. Checkmates Live Chess Game",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/checkmates/2.PNG",
        alt: "Checkmates Game Opponent found",
        text: "2. Checkmates Game Opponent found",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/checkmates/3.PNG",
        alt: "Checkmates New Game page",
        text: "3. Checkmates New Game page",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/checkmates/4.PNG",
        alt: "Checkmates Game Ended",
        text: "4. Checkmates Game Ended",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/checkmates/5.PNG",
        alt: "Checkmates Leaderboard",
        text: "5. Checkmates Leaderboard",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/checkmates/6.PNG",
        alt: "Checkmates Homepage",
        text: "6. Checkmates Homepage",
        width: 1080,
        height: 1920,
      },
    ],
    homepage: true,
    links: [
      {
        type: LINK_TYPE.WEBSITE,
        url: "https://checkmat.es",
      },
      {
        type: LINK_TYPE.FARCASTER,
        url: "https://farcaster.xyz/miniapps/ceoeKAzVgRwc/checkmates",
      },
    ],
  },
  {
    name: "Drift",
    slug: "drift",
    description:
      "Stablecoin-native POS and payment gateway with automatic offramps.",
    markdownPath: "content/drift.mdx",
    color: "#6C3BF5",
    image: "/projects/drift/preview.png",
    tags: [PROJECT_TAG.INTERNAL, PROJECT_TAG.PAYMENTS, PROJECT_TAG.STABLECOINS],
    homepage: false,
    links: [
      {
        type: LINK_TYPE.WEBSITE,
        url: "https://drift.money/",
      },
      {
        type: LINK_TYPE.TWITTER,
        url: "https://x.com/drift_money",
      },
    ],
  },
  {
    name: "Eco",
    slug: "eco",
    description:
      "A checkout app for merchants that leverages Eco's cross-chain stablecoins payment technology.",
    markdownPath: "content/eco.mdx",
    color: "#325691",
    image: "/projects/eco/preview.png",
    screenshotUrls: [
      {
        url: "/projects/eco/1.png",
        alt: "Eco Checkout payment details",
        text: "1. Eco checkout payment details selection",
        width: 1920,
        height: 1080,
      },
      {
        url: "/projects/eco/2.png",
        alt: "Eco Checkout connect wallet",
        text: "2. Eco checkout wallet connection",
        width: 1920,
        height: 1080,
      },
      {
        url: "/projects/eco/3.png",
        alt: "Eco Checkout tokens found",
        text: "3. Tokens found in the user's wallet",
        width: 1920,
        height: 1080,
      },
    ],
    tags: [
      PROJECT_TAG.EXTERNAL,
      PROJECT_TAG.PAYMENTS,
      PROJECT_TAG.STABLECOINS,
      PROJECT_TAG.MERCHANT,
      PROJECT_TAG.CROSS_CHAIN,
    ],
    homepage: false,
    links: [
      {
        type: LINK_TYPE.WEBSITE,
        url: "https://www.ecocheckout.xyz/",
      },
    ],
  },
  {
    name: "Griv",
    slug: "griv",
    description: "Griv - For the ones that show up.",
    markdownPath: "content/griv.mdx",
    color: "#1E1E1E",
    image: "/projects/griv/preview.png",
    heroImage: "/projects/griv/hero.png",
    tags: [
      PROJECT_TAG.EXTERNAL,
      PROJECT_TAG.SOCIAL,
      PROJECT_TAG.HEALTH,
      PROJECT_TAG.FITNESS,
      PROJECT_TAG.SPORTS,
      PROJECT_TAG.LEADERBOARDS,
    ],
    homepage: true,
    screenshotUrls: [
      {
        url: "/projects/griv/1.jpg",
        alt: "Griv Camera",
        text: "1. Shoot your commitment",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/griv/2.jpg",
        alt: "Griv Profile",
        text: "2. Explore your profile",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/griv/3.jpg",
        alt: "Griv Leaderboard",
        text: "3. Compete",
        width: 1080,
        height: 1920,
      },
    ],
    links: [
      {
        type: LINK_TYPE.WEBSITE,
        url: "https://griv.gg",
      },
      {
        type: LINK_TYPE.FARCASTER,
        url: "https://farcaster.xyz/miniapps/KtCKyy4lk104/griv",
      },
      {
        type: LINK_TYPE.TWITTER,
        url: "https://x.com/grivapp",
      },
    ],
  },
  {
    name: "UFO",
    slug: "ufo",
    description: "UFO.fm - the open internet radio",
    markdownPath: "content/ufo.mdx",
    color: "#1E1E1E",
    image: "/projects/ufo/preview.png",
    heroImage: "/projects/ufo/hero.png",
    screenshotUrls: [
      {
        url: "/projects/ufo/1.jpg",
        alt: "UFO Home",
        text: "1. Check the current episode",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/ufo/2.jpg",
        alt: "UFO Channels",
        text: "2. Explore the channels",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/ufo/3.jpg",
        alt: "UFO broadcasts",
        text: "3. Listen to the previous broadcasts",
        width: 1080,
        height: 1920,
      },
    ],
    tags: [
      PROJECT_TAG.EXTERNAL,
      PROJECT_TAG.RADIO,
      PROJECT_TAG.MUSIC,
      PROJECT_TAG.PODCASTS,
      PROJECT_TAG.LIVESTREAMS,
    ],
    homepage: true,
    links: [
      {
        type: LINK_TYPE.WEBSITE,
        url: "https://ufo.fm/",
      },
      {
        type: LINK_TYPE.FARCASTER,
        url: "https://farcaster.xyz/miniapps/0r6DJZlzhP-D/ufo",
      },
      {
        type: LINK_TYPE.TWITTER,
        url: "https://x.com/ufo__club",
      },
    ],
  },
  {
    name: "ACID TEST",
    slug: "acid-test",
    description:
      "An onchain radio show bringing music, conversation and creative energy to Farcaster.",
    markdownPath: "content/acid-test.mdx",
    color: "#000000",
    image: "/projects/acid-test/preview.png",
    heroImage: "/projects/acid-test/hero.jpg",
    tags: [
      PROJECT_TAG.EXTERNAL,
      PROJECT_TAG.RADIO,
      PROJECT_TAG.MUSIC,
      PROJECT_TAG.PODCASTS,
    ],
    homepage: false,
    screenshotUrls: [
      {
        url: "/projects/acid-test/1.jpg",
        alt: "Acid Test Episodes",
        text: "1. Browse the weekly episodes",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/acid-test/2.jpg",
        alt: "Acid Test player",
        text: "2. Listen to episodes",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/acid-test/3.jpg",
        alt: "Acid Test collectors",
        text: "3. View collectors and mint statistics",
        width: 1080,
        height: 1920,
      },
    ],
    links: [
      {
        type: LINK_TYPE.WEBSITE,
        url: "https://app.acidtest.xyz/",
      },
      {
        type: LINK_TYPE.FARCASTER,
        url: "https://farcaster.xyz/miniapps/fTRKM7quo7RZ/acid-test",
      },
      {
        type: LINK_TYPE.TWITTER,
        url: "https://x.com/acid____test",
      },
    ],
  },
  {
    name: "Betttr",
    slug: "betttr",
    description:
      "A Farcaster mini-app sports prediction market. Bet, prove your skills, and earn.",
    markdownPath: "content/betttr.mdx",
    color: "#CCCCCC",
    image: "/projects/betttr/preview.png",
    heroImage: "/projects/betttr/hero.png",
    tags: [PROJECT_TAG.INTERNAL, PROJECT_TAG.SPORTS, PROJECT_TAG.BETS],
    screenshotUrls: [
      {
        url: "/projects/betttr/1.png",
        alt: "Betttr Home",
        text: "1. Betttr Homepage",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/betttr/2.png",
        alt: "Betttr Combo Bet",
        text: "2. Betttr Combo Bet cart",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/betttr/3.png",
        alt: "Betttr User Profile",
        text: "3. Betttr user profile",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/betttr/4.png",
        alt: "Betttr Leaderboard",
        text: "4. Betttr leaderboard",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/betttr/5.png",
        alt: "Betttr My Bets",
        text: "5. Betttr My Bets page",
        width: 1080,
        height: 1920,
      },
    ],
    homepage: false,
    links: [
      {
        type: LINK_TYPE.WEBSITE,
        url: "https://betttr.xyz",
      },
      {
        type: LINK_TYPE.FARCASTER,
        url: "https://farcaster.xyz/miniapps/3d_l4HanGz-0/betttr",
      },
    ],
  },
  {
    name: "OD Passport",
    slug: "od-passport",
    description:
      "A web app for issuing, managing, and collecting onchain badges as EAS attestations.",
    markdownPath: "content/od-passport.mdx",
    color: "#E7F5FE",
    image: "/projects/od-passport/preview.png",
    screenshotUrls: [
      {
        url: "/projects/od-passport/1.png",
        alt: "OD view badges",
        text: "1. View your badges",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/od-passport/2.png",
        alt: "OD issue badge",
        text: "2. Issue new badge (as admin)",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/od-passport/3.png",
        alt: "OD badge details",
        text: "3. View badge details",
        width: 1080,
        height: 1920,
      },
    ],
    tags: [PROJECT_TAG.EXTERNAL, PROJECT_TAG.IDENTITY, PROJECT_TAG.SOCIAL],
    homepage: false,
    links: [
      {
        type: LINK_TYPE.GITHUB,
        url: "https://github.com/builders-garden/od-passport-app",
      },
      {
        type: LINK_TYPE.YOUTUBE,
        url: "https://www.youtube.com/watch?v=IzBVjqCzVp8",
      },
    ],
  },
  {
    name: "Zuland",
    slug: "zuland",
    description: "Token-gated and encrypted social spaces for ZuVillages.",
    markdownPath: "content/zuland.mdx",
    color: "#1E1E1E",
    image: "/projects/zuland/preview.png",
    screenshotUrls: [
      {
        url: "/projects/zuland/1.png",
        alt: "Zuland Home",
        text: "1. Zuland Home",
        width: 1920,
        height: 1080,
      },
    ],
    tags: [PROJECT_TAG.EXTERNAL, PROJECT_TAG.SOCIAL, PROJECT_TAG.PRIVACY],
    homepage: false,
    links: [
      {
        type: LINK_TYPE.WEBSITE,
        url: "https://www.zuzalu.city/",
      },
      {
        type: LINK_TYPE.GITHUB,
        url: "https://github.com/builders-garden/Zuzalu-City",
      },
      {
        type: LINK_TYPE.TWITTER,
        url: "https://x.com/Zuzalu_city",
      },
    ],
  },
  {
    name: "Stringz",
    slug: "stringz",
    description: "Stringz - Finally enjoy Reddit-style threads on Farcaster.",
    markdownPath: "content/stringz.mdx",
    color: "#FA4200",
    image: "/projects/stringz/preview.png",
    heroImage: "/projects/stringz/hero.png",
    screenshotUrls: [
      {
        url: "/projects/stringz/1.png",
        alt: "Stringz Thread",
        text: "1. Read thread",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/stringz/2.png",
        alt: "Stringz Profile",
        text: "2. Explore your profile",
        width: 1080,
        height: 1920,
      },
    ],
    tags: [PROJECT_TAG.INTERNAL, PROJECT_TAG.SOCIAL],
    homepage: false,
    links: [
      {
        type: LINK_TYPE.GITHUB,
        url: "https://github.com/builders-garden/stringz",
      },
    ],
  },
  // {
  //   name: "Ethereum Daily",
  //   slug: "eth-daily",
  //   description:
  //     "A mini app where users read daily articles and take quizzes to earn rewards.",
  //   markdownPath: "content/eth-daily.mdx",
  //   color: "#627EEA",
  //   image: "/projects/eth-daily/preview.png",
  //   heroImage: "/projects/eth-daily/hero.jpg",
  //   screenshotUrls: [
  //     {
  //       url: "/projects/eth-daily/1.jpg",
  //       alt: "Ethereum Daily Home",
  //       text: "1. Check the rewards and read the article",
  //       width: 1080,
  //       height: 1920,
  //     },
  //     {
  //       url: "/projects/eth-daily/2.jpg",
  //       alt: "Ethereum Daily Quiz",
  //       text: "2. Answer the quiz questions",
  //       width: 1080,
  //       height: 1920,
  //     },
  //     {
  //       url: "/projects/eth-daily/3.jpg",
  //       alt: "Ethereum Daily Quiz Results",
  //       text: "3. Earn rewards based on your performance",
  //       width: 1080,
  //       height: 1920,
  //     },
  //   ],
  //   tags: [PROJECT_TAG.EXTERNAL, PROJECT_TAG.GAME, PROJECT_TAG.NEWS],
  //   homepage: false,
  //   links: [
  //     {
  //       type: LINK_TYPE.WEBSITE,
  //       url: "https://paragraph.com/@ethereumdaily",
  //     },
  //     {
  //       type: LINK_TYPE.FARCASTER,
  //       url: "https://farcaster.xyz/ethereumdaily.eth",
  //     },
  //     {
  //       type: LINK_TYPE.TWITTER,
  //       url: "https://x.com/EthereumDaily_",
  //     },
  //   ],
  // },
  {
    name: "ITM ID",
    slug: "itm",
    description:
      "See your echoes, moments and check-in to events easily with ITM ID",
    markdownPath: "content/itm.mdx",
    color: "#000000",
    image: "/projects/itm/preview.png",
    // heroImage: "/projects/itm/hero.jpg",
    screenshotUrls: [
      {
        url: "/projects/itm/1.png",
        alt: "ITM ID Landing page",
        text: "1. ITM ID Landing page",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/itm/2.png",
        alt: "ITM ID Echoes Feed",
        text: "2. Your ITM Echoes Feed",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/itm/3.png",
        alt: "ITM ID Moments",
        text: "3. The Moments you already attended",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/itm/4.png",
        alt: "ITM ID Upcoming Moments",
        text: "4. The Upcoming Moments",
        width: 1080,
        height: 1920,
      },
      {
        url: "/projects/itm/5.png",
        alt: "ITM ID Today Moments",
        text: "5. The Moments happening today",
        width: 1080,
        height: 1920,
      },
    ],
    tags: [
      PROJECT_TAG.EXTERNAL,
      PROJECT_TAG.CHECK_IN,
      PROJECT_TAG.IRL,
      PROJECT_TAG.EVENTS,
    ],
    homepage: true,
    links: [
      {
        type: LINK_TYPE.FARCASTER,
        url: "https://farcaster.xyz/?launchFrameUrl=https%3A%2F%2Fitm-id-miniapp.vercel.app",
      },
    ],
  },
];
