export const MEMBERS = [
  {
    name: "frank",
    description: "Blockchain Developer",
    twitter: "https://twitter.com/Frankc_eth",
    farcaster: "https://warpcast.com/frankk",
    image: "/team/frank.jpg",
  },
  {
    name: "limone",
    description: "Full Stack Developer",
    twitter: "https://twitter.com/limone_eth",
    farcaster: "https://warpcast.com/limone.eth",
    url: "https://limone.lol",
    image: "/team/limone.png",
  },
  {
    name: "orbulo",
    description: "Full Stack Developer",
    twitter: "https://twitter.com/orbuloeth",
    farcaster: "https://warpcast.com/orbulo",
    url: "https://paolorollo.dev",
    image: "/team/orbulo.jpg",
  },
  {
    name: "flurry",
    description: "Business",
    twitter: "https://twitter.com/mctflurryy",
    farcaster: "https://warpcast.com/mctflurry",
    image: "/team/flurry.png",
  },
  {
    name: "fraye",
    description: "Backend Developer",
    twitter: "https://twitter.com/itsmide_eth",
    farcaster: "https://warpcast.com/itsmide.eth",
    url: "https://midena.dev",
    image: "/team/fraye.jpg",
  },
  {
    name: "bianc8",
    description: "Full Stack Developer",
    twitter: "https://twitter.com/bianc8_eth",
    farcaster: "https://warpcast.com/bianc8",
    url: "https://biancotto.eu",
    image: "/team/bianc8.jpg",
  },
  {
    name: "blackicon",
    description: "Fullstack Developer",
    twitter: "https://twitter.com/TBlackicon",
    farcaster: "https://warpcast.com/blackicon.eth",
    image: "/team/blackicon.png",
  },
  {
    name: "caso",
    description: "Frontend Developer",
    twitter: "https://twitter.com/steven_basalari",
    farcaster: "https://warpcast.com/0xcaso",
    url: "https://matteocasonato.com/",
    image: "/team/caso.png",
  },
  {
    name: "drone",
    description: "Solidity Developer",
    twitter: "https://twitter.com/SolidityDrone",
    farcaster: "https://warpcast.com/drone",
    image: "/team/drone.jpg",
  },
  {
    name: "stepome",
    description: "UX/UI Designer",
    twitter: "https://twitter.com/stefanopomelli",
    farcaster: "https://warpcast.com/stepome",
    url: "https://stefanopomelli.com/",
    image: "/team/stepome.jpg",
  },
];
